### ISSUE TITLE
Configurable mount point, /tmp management

### ISSUE THREAD

**Issue by rclark** [mapbox/ec2mnt#3]
Very common to see our machines mount in different locations. We could make this an optional setting? Frankly I'd prefer to just do it in one place for every project... is that smarter?

Also very common to see `/tmp` folders places on the mounted volume. Any reason not to include that logic here?

cc @yhahn

**Comment by yhahn** [comment]
I'm down with:
1. One place for every project
2. Ensuring `/tmp` is put on the mounted instance drives

Where the intention is for projects to use `/tmp` and be agnostic to other drive/mount point setup (?)
