### ISSUE TITLE
Publish via npm

### ISSUE THREAD

**Issue by freenerd** [mapbox/ec2mnt#6]
Even though it's convenient to [run directly from S3](https://github.com/mapbox/ec2mnt#run-from-s3), in terms of reliability it would be better to distribute this package via `npm` and make it installable from there. Then it can be vendored into applications without a runtime call to S3.

/cc @rclark @karenzshea

**Comment by yhahn** [comment]
Can you expand on this? Our slugs are downloaded via a runtime call to s3 so our vendor-style bundling of ec2mnt would be vulnerable to the same source of unreliability, right?

Is it that we need an example where there's some awscli-built in retry like

> $ aws s3 cp s3://mapbox/apps/ec2mnt/v1.1.0 - | bash

?

**Comment by freenerd** [comment]
The problem is cross-regional S3 access, which has potential for being slow or unreliable. Retries will likely help, but vendoring into the slug (which downloads from a local region) will the safest option. Since ec2mnt is in the critical path for launching an instance, I think we should not take risks.

**Comment by yhahn** [comment]
Ah, makes sense :+1:
